const DEFAULT_LOCATION_NAME = "Kuala Lumpur";
const DEFAULT_LAT = 3.139;
const DEFAULT_LNG = 101.686;
const DEFAULT_ZOOM = 12;

export { DEFAULT_LOCATION_NAME, DEFAULT_LAT, DEFAULT_LNG, DEFAULT_ZOOM };
